const REACT_APP_PUSHER_APP_ID = "918424";
const REACT_APP_PUSHER_APP_KEY = "d64066063604037f3db4";
const REACT_APP_PUSHER_APP_SECRET = "9b63f0fbaf9699efd064";
const REACT_APP_PUSHER_APP_CLUSTER = "us2";

// # GOOGLE MAPS API CREDENTIALS
const REACT_APP_GMAPS_API_KEY = "AIzaSyDgrD2T5T3aXS3rG7hHrW5dtabt4gicJGk";

exports.secret = {
  REACT_APP_PUSHER_APP_ID,
  REACT_APP_PUSHER_APP_KEY,
  REACT_APP_PUSHER_APP_SECRET,
  REACT_APP_PUSHER_APP_CLUSTER
}